/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sistema_gestion_ventas;

import com.sistema_gestion_ventas.usuario.application.AutenticarUsuarioUseCase;
import com.sistema_gestion_ventas.usuario.infrastructure.out.UsuarioRepository;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jhon
 */
public class Main extends javax.swing.JFrame {
    private AutenticarUsuarioUseCase autenticarUsuarioUseCase;
    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
        UsuarioRepository usuarioRepository = new UsuarioRepository(); // Repositorio de usuario
        autenticarUsuarioUseCase = new AutenticarUsuarioUseCase(usuarioRepository);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        Login = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Iniciar Sesión");
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 101));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/software(1).png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        passwordText.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        passwordText.setForeground(new java.awt.Color(0, 0, 0));
        passwordText.setText("Contraseña");
        background.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        usernameText.setFont(new java.awt.Font("FreeSans", 0, 18)); // NOI18N
        usernameText.setForeground(new java.awt.Color(0, 0, 0));
        usernameText.setText("Usuario");
        background.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        usernameField.setBackground(new java.awt.Color(255, 255, 255));
        usernameField.setForeground(new java.awt.Color(153, 153, 153));
        usernameField.setText("Ingrese su nombre de usuario");
        usernameField.setToolTipText("");
        usernameField.setBorder(null);
        usernameField.setCaretColor(new java.awt.Color(0, 0, 0));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameFieldMousePressed(evt);
            }
        });
        background.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 530, 30));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 520, 20));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 520, 20));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("********************");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(0, 0, 0));
        passwordField.setPreferredSize(new java.awt.Dimension(125, 12));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordFieldMousePressed(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        background.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 520, 30));

        Login.setBackground(new java.awt.Color(153, 153, 255));

        LoginText.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        LoginText.setForeground(new java.awt.Color(0, 0, 0));
        LoginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginText.setText("Entrar");
        LoginText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginText, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMousePressed
        if (usernameField.getText().equals("Ingrese su nombre de usuario")){
            usernameField.setText("");
            usernameField.setForeground(Color.black);
        }
        if (String.valueOf(passwordField.getPassword()).isEmpty()) {
            passwordField.setText("********************");
            passwordField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usernameFieldMousePressed

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        
    }//GEN-LAST:event_passwordFieldFocusLost

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        
    }//GEN-LAST:event_usernameFieldFocusLost

    private void passwordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMousePressed
        if (String.valueOf(passwordField.getPassword()).equals("********************")) {
            passwordField.setText("");
            passwordField.setForeground(Color.black);
        }
        if (usernameField.getText().isEmpty()) {
            usernameField.setText("Ingrese su nombre de usuario");
            usernameField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordFieldMousePressed

    private void LoginTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginTextMouseClicked
        // Obtener el nombre de usuario y la contraseña de los campos de texto
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword()).trim(); // Convierte el array de chars a String

        // Verifica que los campos no estén vacíos
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su nombre de usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Autenticar el usuario utilizando AutenticarUsuarioUseCase
        if (autenticarUsuarioUseCase.execute(username, password).isPresent()) {
            JOptionPane.showMessageDialog(this, "¡Inicio de sesión exitoso!");
            new MenuPrincipal().setVisible(true);  // Mostrar el menú principal
            dispose();  // Cierra la ventana de login
        } else {
            JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JLabel LoginText;
    private javax.swing.JPanel background;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
